// Code generated by goctl. DO NOT EDIT.
package types

type ActivityReq struct {
	HotelId   int64  `form:"hotelId"`
	Year      int    `form:"year"`
	Month     int    `form:"month"`
	VenueType string `form:"venueType,optional"`
}

type ActivityResp struct {
	List []DailyActivity `json:"list"`
}

type AdminThresholdReq struct {
	HotelId int64 `path:"hotelId"`
}

type AdminUserIdReq struct {
	Id int64 `path:"id"`
}

type AdminUserItem struct {
	Id             int64   `json:"id"`
	Name           string  `json:"name"`
	Email          string  `json:"email"`
	Phone          string  `json:"phone"`
	Status         string  `json:"status"`
	HotelIds       []int64 `json:"hotelIds"`
	RoleId         int64   `json:"roleId"`
	PrimaryHotelId int64   `json:"primaryHotelId"`
}

type AdminUserListResp struct {
	List []AdminUserItem `json:"list"`
}

type BaseResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type CityEventItem struct {
	VenueName string `json:"venueName"`
	EventName string `json:"eventName"`
	EventType string `json:"eventType"`
}

type CityEventReq struct {
	Date string `form:"date"` // YYYY-MM-DD
	City string `form:"city"`
}

type CityEventResp struct {
	List []CityEventItem `json:"list"`
}

type CompetitorDetailReq struct {
	Date    string `form:"date"`
	GroupId int64  `form:"groupId,optional"`
	HotelId int64  `form:"hotelId,optional"`
}

type CompetitorDetailResp struct {
	List []CompetitorHotelDetail `json:"list"`
}

type CompetitorHotelDetail struct {
	HotelName    string               `json:"hotelName"`
	ActivityType string               `json:"activityType"`
	Count        int                  `json:"count"`
	Activities   []CompetitorActivity `json:"activities"`
}

type CompetitorActivity struct {
	VenueName     string `json:"venueName"`
	Period        string `json:"period"`
	Date          string `json:"date"`
	EventName     string `json:"eventName"`     // 活动名称（来自 Hotel Event 表）
	EventType     string `json:"eventType"`     // 活动类型
	BookingStatus string `json:"bookingStatus"` // 预订状态
}

type CreateEmailGroupReq struct {
	Name    string             `json:"name"`
	HotelId int64              `json:"hotelId"`
	Scene   string             `json:"scene,optional"`
	Members []EmailGroupMember `json:"members"`
}

type CreateHotelReq struct {
	Name         string `json:"name"`
	City         string `json:"city"`
	MarketAreaId int64  `json:"marketAreaId"`
}

type CreateScheduleReq struct {
	GroupId  int64  `json:"groupId"`
	CronExpr string `json:"cronExpr"`
	Enabled  bool   `json:"enabled"`
}

type DailyActivity struct {
	Date            string     `json:"date"`
	Hotel           PeriodData `json:"hotel"`
	CompetitorTotal PeriodData `json:"competitorTotal"` // 竞对用总值
	MarketTotal     PeriodData `json:"marketTotal"`     // 商圈用总值
	CityEventCount  int        `json:"cityEventCount"`
}

type DailyOccupancy struct {
	Date           string     `json:"date"` // YYYY-MM-DD
	Hotel          PeriodData `json:"hotel"`
	CompetitorAvg  PeriodData `json:"competitorAvg"`
	MarketAvg      PeriodData `json:"marketAvg"`
	CityEventCount int        `json:"cityEventCount"`
}

type DingTalkLoginReq struct {
	Code string `json:"code"`
}

type DingTalkLoginResp struct {
	Token    string  `json:"token"`
	Name     string  `json:"name"`
	Status   string  `json:"status"`
	HotelIds []int64 `json:"hotelIds"`
}

type EmailGroupIdReq struct {
	Id int64 `path:"id"`
}

type EmailGroupItem struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	HotelId     int64  `json:"hotelId"`
	HotelName   string `json:"hotelName"`
	Scene       string `json:"scene"`
	MemberCount int    `json:"memberCount"`
}

type EmailGroupListReq struct {
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=10"`
	Keyword  string `form:"keyword,optional"`
}

type EmailGroupListResp struct {
	List  []EmailGroupItem `json:"list"`
	Total int64            `json:"total"`
}

type EmailGroupMember struct {
	UserId int64  `json:"userId"`
	Name   string `json:"name"`
	Email  string `json:"email"`
}

type EmailGroupMemberListResp struct {
	List []EmailGroupMember `json:"list"`
}

type EmailLogIdReq struct {
	Id int64 `path:"id"`
}

type EmailLogItem struct {
	Id           int64  `json:"id"`
	ScheduleId   int64  `json:"scheduleId"`
	TemplateId   int64  `json:"templateId"`
	TemplateName string `json:"templateName"`
	Source       string `json:"source"`        // 'blast' / 'group:<id>' / 'retry:<id>' / 'legacy'
	SourceLabel  string `json:"sourceLabel"`   // 中文展示，比如「全员群发」「邮件组：销售组」「重发」
	Status       string `json:"status"`
	Total        int    `json:"total"`
	FailCount    int    `json:"failCount"`
	RetryCount   int    `json:"retryCount"`
	SentAt       string `json:"sentAt"`
}

type EmailLogListReq struct {
	Page     int `form:"page,optional,default=1"`
	PageSize int `form:"pageSize,optional,default=20"`
}

type EmailLogListResp struct {
	List  []EmailLogItem `json:"list"`
	Total int64          `json:"total"`
}

type EmailScheduleItem struct {
	Id        int64  `json:"id"`
	GroupId   int64  `json:"groupId"`
	GroupName string `json:"groupName"`
	CronExpr  string `json:"cronExpr"`
	Enabled   bool   `json:"enabled"`
}

type EmailScheduleListResp struct {
	List []EmailScheduleItem `json:"list"`
}

type ScheduleIdReq struct {
	Id int64 `path:"id"`
}

type SendToUserReq struct {
	UserId       int64  `json:"userId,optional"`
	Email        string `json:"email,optional"`
	Name         string `json:"name,optional"`
	TemplateName string `json:"templateName,optional"`
	HotelId      int64  `json:"hotelId,optional"`
}

type FailListResp struct {
	List []FailListItem `json:"list"`
}

type FailListItem struct {
	Email string `json:"email"`
	Error string `json:"error"`
}

type HotelDetailItem struct {
	VenueName    string `json:"venueName"`
	Period       string `json:"period"` // AM/PM/EV
	ActivityType string `json:"activityType"`
	IsBooked     bool   `json:"isBooked"`
}

type HotelDetailReq struct {
	Date      string `form:"date"`
	HotelId   int64  `form:"hotelId"`
	VenueType string `form:"venueType,optional"`
}

type HotelDetailResp struct {
	List []HotelDetailItem `json:"list"`
}

type HotelItem struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	City         string `json:"city"`
	MarketAreaId int64  `json:"marketAreaId"`
}

type HotelListResp struct {
	List []HotelItem `json:"list"`
}

type OccupancyReq struct {
	HotelId   int64  `form:"hotelId"`
	Year      int    `form:"year"`
	Month     int    `form:"month"`
	VenueType string `form:"venueType,optional"` // all 或具体场地类型
}

type OccupancyResp struct {
	List    []DailyOccupancy `json:"list"`
	Summary OccupancySummary `json:"summary"`
}

// OccupancySummary 月度汇总（按 venue 加权：∑booked / ∑total）
type OccupancySummary struct {
	HotelRate      float64 `json:"hotelRate"`      // 本酒店月度出租率 0-100
	CompetitorRate float64 `json:"competitorRate"` // 竞对群月度出租率 0-100
	MarketRate     float64 `json:"marketRate"`     // 商圈月度出租率 0-100
}

type PeriodData struct {
	M float64 `json:"m"` // 上午
	A float64 `json:"a"` // 下午
	E float64 `json:"e"` // 晚上
}

type SaveThresholdReq struct {
	HotelId int64           `json:"hotelId,optional"`
	List    []ThresholdItem `json:"list"`
}

type ThresholdItem struct {
	MetricType string  `json:"metricType"` // occupancy / activity
	Level      string  `json:"level"`      // low / medium / high
	MinValue   float64 `json:"minValue"`
	MaxValue   float64 `json:"maxValue"`
	Color      string  `json:"color"` // 十六进制色号
}

type ThresholdReq struct {
	HotelId int64 `form:"hotelId,optional"`
}

type ThresholdResp struct {
	List []ThresholdItem `json:"list"`
}

type UpdateEmailGroupReq struct {
	Id      int64              `path:"id"`
	Name    string             `json:"name"`
	HotelId int64              `json:"hotelId"`
	Scene   string             `json:"scene,optional"`
	Members []EmailGroupMember `json:"members"`
}

type UpdateScheduleReq struct {
	Id       int64  `path:"id"`
	GroupId  int64  `json:"groupId,optional"`
	CronExpr string `json:"cronExpr"`
	Enabled  bool   `json:"enabled"`
}

type UpdateUserHotelsReq struct {
	Id       int64   `path:"id"`
	HotelIds []int64 `json:"hotelIds"`
}

type UpdateUserStatusReq struct {
	Id     int64  `path:"id"`
	Status string `json:"status"` // active / disabled
}

type UserHotelItem struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	City string `json:"city"`
}

type UserInfoResp struct {
	Id       int64           `json:"id"`
	Name     string          `json:"name"`
	Email    string          `json:"email"`
	Status   string          `json:"status"`
	HotelIds []int64         `json:"hotelIds"`
	Hotels   []UserHotelItem `json:"hotels"`
	IsAdmin  bool            `json:"isAdmin"`
	RoleId   int64           `json:"roleId"`
	RoleName string          `json:"roleName"`
	Menus    []string        `json:"menus"`
}

type SyncTriggerResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type SyncStatusResp struct {
	LastSyncAt string `json:"lastSyncAt"`
	Status     string `json:"status"`
	Message    string `json:"message"`
	NextRunAt  string `json:"nextRunAt"`
}

type SyncScheduleResp struct {
	CronExpr string `json:"cronExpr"`
	Enabled  bool   `json:"enabled"`
	NextRun  string `json:"nextRun"`
}

type UpdateSyncScheduleReq struct {
	CronExpr string `json:"cronExpr"`
	Enabled  bool   `json:"enabled"`
}

type UpdateCheckScheduleResp struct {
	CronExpr string `json:"cronExpr"`
	Enabled  bool   `json:"enabled"`
	NextRun  string `json:"nextRun"`
}

type UpdateUpdateCheckScheduleReq struct {
	CronExpr string `json:"cronExpr"`
	Enabled  bool   `json:"enabled"`
}

type RoleItem struct {
	Id    int64    `json:"id"`
	Name  string   `json:"name"`
	Label string   `json:"label"`
	Menus []string `json:"menus"`
	Apis  []string `json:"apis"`
}

type RoleListResp struct {
	List []RoleItem `json:"list"`
}

type CreateRoleReq struct {
	Name  string   `json:"name"`
	Label string   `json:"label"`
	Menus []string `json:"menus"`
	Apis  []string `json:"apis"`
}

type UpdateRoleReq struct {
	Id    int64    `path:"id"`
	Name  string   `json:"name"`
	Label string   `json:"label"`
	Menus []string `json:"menus"`
	Apis  []string `json:"apis"`
}

type UpdateUserRoleReq struct {
	Id     int64 `path:"id"`
	RoleId int64 `json:"roleId"`
}

type UpdateUserEmailReq struct {
	Id    int64  `path:"id"`
	Email string `json:"email"`
}

type UpdateUserPhoneReq struct {
	Id    int64  `path:"id"`
	Phone string `json:"phone"`
}

type UpdateUserPrimaryHotelReq struct {
	Id             int64 `path:"id"`
	PrimaryHotelId int64 `json:"primaryHotelId"` // 0 表示清除
}

type CreateAdminUserReq struct {
	Username       string `json:"username"`
	Password       string `json:"password"`
	Email          string `json:"email,optional"`
	Phone          string `json:"phone,optional"`
	RoleId         int64  `json:"roleId,optional"`
	PrimaryHotelId int64  `json:"primaryHotelId,optional"`
}

type MailTemplateItem struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Subject     string `json:"subject"`
	Body        string `json:"body"`
	Description string `json:"description"`
}

type MailTemplateListResp struct {
	List []MailTemplateItem `json:"list"`
}

type CreateMailTemplateReq struct {
	Name        string `json:"name"`
	Subject     string `json:"subject"`
	Body        string `json:"body"`
	Description string `json:"description,optional"`
}

type UpdateMailTemplateReq struct {
	Id          int64  `path:"id"`
	Name        string `json:"name"`
	Subject     string `json:"subject"`
	Body        string `json:"body"`
	Description string `json:"description,optional"`
}

type MailTemplateIdReq struct {
	Id int64 `path:"id"`
}

type MailSettingResp struct {
	SmtpHost string `json:"smtpHost"`
	SmtpPort int    `json:"smtpPort"`
	Username string `json:"username"`
	Password string `json:"password"`
	FromName string `json:"fromName"`
}

type UpdateMailSettingReq struct {
	SmtpHost string `json:"smtpHost"`
	SmtpPort int    `json:"smtpPort"`
	Username string `json:"username"`
	Password string `json:"password,optional"`
	FromName string `json:"fromName"`
}
