// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	admin "meeting/internal/handler/admin"
	auth "meeting/internal/handler/auth"
	dashboard "meeting/internal/handler/dashboard"
	email "meeting/internal/handler/email"
	synchandler "meeting/internal/handler/sync"
	"meeting/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.AdminOnly},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/admin/hotels",
					Handler: admin.ListHotelsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/admin/hotels",
					Handler: admin.CreateHotelHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/admin/thresholds/:hotelId",
					Handler: admin.GetAdminThresholdsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/admin/thresholds/:hotelId",
					Handler: admin.SaveAdminThresholdsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/admin/users",
					Handler: admin.ListAdminUsersHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/admin/users/:id/hotels",
					Handler: admin.UpdateUserHotelsHandler(serverCtx),
				},
			{
				Method:  http.MethodPut,
				Path:    "/api/admin/users/:id/status",
				Handler: admin.UpdateUserStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/admin/users/:id/role",
				Handler: admin.UpdateUserRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/admin/users/:id/email",
				Handler: admin.UpdateUserEmailHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/admin/users/:id/phone",
				Handler: admin.UpdateUserPhoneHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/users",
				Handler: admin.CreateAdminUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/roles",
				Handler: admin.ListRolesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/roles",
				Handler: admin.CreateRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/admin/roles/:id",
				Handler: admin.UpdateRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/mail-setting",
				Handler: admin.GetMailSettingHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/admin/mail-setting",
				Handler: admin.UpdateMailSettingHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/mail-templates",
				Handler: admin.ListMailTemplatesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/mail-templates",
				Handler: admin.CreateMailTemplateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/admin/mail-templates/:id",
				Handler: admin.UpdateMailTemplateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/admin/mail-templates/:id",
				Handler: admin.DeleteMailTemplateHandler(serverCtx),
			},
				{
					Method:  http.MethodPost,
					Path:    "/api/admin/sync/trigger",
					Handler: synchandler.TriggerSyncHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/admin/sync/status",
					Handler: synchandler.GetSyncStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/admin/sync/schedule",
					Handler: synchandler.GetSyncScheduleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/admin/sync/schedule",
					Handler: synchandler.UpdateSyncScheduleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/admin/notifications",
					Handler: admin.ListNotificationSettingsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/admin/notifications/:channel",
					Handler: admin.UpdateNotificationSettingHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/admin/notifications/:channel/test",
					Handler: admin.TestNotificationHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/admin/update-checks",
					Handler: admin.ListUpdateChecksHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/admin/update-checks/trigger",
					Handler: admin.TriggerUpdateCheckHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/admin/update-checks/schedule",
					Handler: admin.GetUpdateCheckScheduleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/admin/update-checks/schedule",
					Handler: admin.UpdateUpdateCheckScheduleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/admin/mail-blast/schedule",
					Handler: admin.GetMailBlastScheduleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/admin/mail-blast/schedule",
					Handler: admin.UpdateMailBlastScheduleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/admin/mail-blast/trigger",
					Handler: admin.TriggerMailBlastHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/dingtalk-login",
				Handler: auth.DingTalkLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/auth/dev-token",
				Handler: auth.DevTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/admin-login",
				Handler: auth.AdminLoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/auth/me",
					Handler: dashboard.GetMeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/config/thresholds",
					Handler: dashboard.GetThresholdsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/dashboard/activity",
					Handler: dashboard.GetActivityHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/dashboard/city-events",
					Handler: dashboard.GetCityEventsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/dashboard/competitor-detail",
					Handler: dashboard.GetCompetitorDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/dashboard/hotel-detail",
					Handler: dashboard.GetHotelDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/dashboard/occupancy",
					Handler: dashboard.GetOccupancyHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/email/groups",
					Handler: email.ListEmailGroupsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/email/groups",
					Handler: email.CreateEmailGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/email/groups/:id",
					Handler: email.UpdateEmailGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/email/groups/:id",
					Handler: email.DeleteEmailGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/email/groups/:id/send",
					Handler: email.SendGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/email/groups/:id/members",
					Handler: email.ListEmailGroupMembersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/email/logs",
					Handler: email.ListEmailLogsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/email/logs/:id/fail-list",
					Handler: email.GetFailListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/email/logs/:id/retry",
					Handler: email.RetryEmailLogHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/email/logs/retry-all-failed",
					Handler: email.RetryAllFailedHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/email/logs/:id/recipients",
					Handler: email.ListLogRecipientsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/email/logs/:logId/recipients/:rid/retry",
					Handler: email.RetryLogRecipientHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/email/schedules",
					Handler: email.ListSchedulesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/email/schedules",
					Handler: email.CreateScheduleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/email/schedules/:id",
					Handler: email.UpdateScheduleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/email/schedules/:id",
					Handler: email.DeleteScheduleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/email/send-to-user",
					Handler: email.SendToUserHandler(serverCtx),
				},
			}...,
		),
	)
}
