// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	admin "meeting/internal/handler/admin"
	auth "meeting/internal/handler/auth"
	dashboard "meeting/internal/handler/dashboard"
	email "meeting/internal/handler/email"
	"meeting/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.AdminOnly},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/admin/hotels",
					Handler: admin.ListHotelsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/admin/hotels",
					Handler: admin.CreateHotelHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/admin/thresholds/:hotelId",
					Handler: admin.GetAdminThresholdsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/admin/thresholds/:hotelId",
					Handler: admin.SaveAdminThresholdsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/admin/users",
					Handler: admin.ListAdminUsersHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/admin/users/:id/hotels",
					Handler: admin.UpdateUserHotelsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/admin/users/:id/status",
					Handler: admin.UpdateUserStatusHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/dingtalk-login",
				Handler: auth.DingTalkLoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/auth/me",
					Handler: dashboard.GetMeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/config/thresholds",
					Handler: dashboard.GetThresholdsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/dashboard/activity",
					Handler: dashboard.GetActivityHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/dashboard/city-events",
					Handler: dashboard.GetCityEventsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/dashboard/competitor-detail",
					Handler: dashboard.GetCompetitorDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/dashboard/hotel-detail",
					Handler: dashboard.GetHotelDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/dashboard/occupancy",
					Handler: dashboard.GetOccupancyHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/email/groups",
					Handler: email.ListEmailGroupsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/email/groups",
					Handler: email.CreateEmailGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/email/groups/:id",
					Handler: email.UpdateEmailGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/email/groups/:id",
					Handler: email.DeleteEmailGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/email/groups/:id/members",
					Handler: email.ListEmailGroupMembersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/email/groups/dimensions",
					Handler: email.GetEmailGroupDimensionsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/email/groups/preview-members",
					Handler: email.PreviewEmailGroupMembersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/email/logs",
					Handler: email.ListEmailLogsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/email/logs/:id/fail-list",
					Handler: email.GetFailListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/email/logs/:id/retry",
					Handler: email.RetryEmailLogHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/email/schedules",
					Handler: email.CreateScheduleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/email/schedules/:id",
					Handler: email.UpdateScheduleHandler(serverCtx),
				},
			}...,
		),
	)
}
